server:
  servlet:
    context-path: /web

spring:
  datasource:
     # \u6570\u636E\u5E93\u8BBF\u95EE\u914D\u7F6E, \u4F7F\u7528druid\u6570\u636E\u6E90
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql:///springboot-example?useUnicode=true&characterEncoding=UTF-8
      username: root
      password: 123456
      #\u8FDE\u63A5\u6C60\u914D\u7F6E
      initial-size: 5
      min-idle: 5
      max-active: 20
      #\u7B49\u5F85\u8D85\u65F6\u65F6\u95F4
      max-wait: 30000
      #\u914D\u7F6E\u68C0\u6D4B\u53EF\u4EE5\u5173\u95ED\u7684\u7A7A\u95F2\u8FDE\u63A5\u7A7A\u95F2\u65F6\u95F4
      time-between-eviction-runs-millis: 60000
      #\u914D\u7F6E\u8FDE\u63A5\u5728\u8FDE\u63A5\u6C60\u4E2D\u6700\u5C0F\u7684\u751F\u5B58\u65F6\u95F4
      min-evictable-idle-time-millis: 300000
      validation-query: select '1' from dual
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # \u6253\u5F00PSCache\uFF0C\u5E76\u4E14\u6307\u5B9A\u6BCF\u4E2A\u8FDE\u63A5\u4E0APSCache\u7684\u5927\u5C0F
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
      # \u914D\u7F6E\u76D1\u63A7\u7EDF\u8BA1\u62E6\u622A\u7684filters, \u53BB\u6389\u540E\u76D1\u63A7\u754C\u9762sql\u65E0\u6CD5\u7EDF\u8BA1, 'wall'\u7528\u4E8E\u9632\u706B\u5899
      filters: stat,wall
      # Spring\u76D1\u63A7AOP\u5207\u5165\u70B9\uFF0C\u5982x.y.z.service.*,\u914D\u7F6E\u591A\u4E2A\u82F1\u6587\u9017\u53F7\u5206\u9694
      aop-patterns: com.ordust.service.*

      # WebStatFilter\u914D\u7F6E
      web-stat-filter:
        enabled: true
        # \u6DFB\u52A0\u8FC7\u6EE4\u89C4\u5219
        url-pattern: /*
        # 忽略过滤的格式
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'

      # StatViewServlet配置
      stat-view-servlet:
        enabled: true
        # 访问路径为/druid时，跳转到StatViewServlet
        url-pattern: /druid/*
        # 是否能够重置数据
        reset-enable: false
        # 需要账号密码才能访问控制台
        login-username: druid
        login-password: druid123

      # 配置StatFilter
      filter:
        stat:
          log-slow-sql: true
  thymeleaf:
    cache: false
mybatis:
  # type-aliases扫描路径
  type-aliases-package: com.ordust.entity
  # mapper xml实现扫描路径
  mapper-locations: classpath:mapper/*.xml
#  property:
#      order: BEFORE

